spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/home/**
