spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: car-service
            uri: lb://car-service
            predicates:
              - Path=/home/**
            filters:
              - TokenRelay
